### ISSUE TITLE
Depends on archived rdp

### ISSUE THREAD

**Issue by tarsius** [skeeto/psl-mode#5]
This package depends on `rdp`, one of the repositories that you recently archived. Should this be archived too?

Also, `psl-mode`, `rdp`, `fakespace` and `mouse-slider-mode` are all being distributed on Melpa. Should we stop doing that?

**Comment by skeeto** [comment]
Thanks for the heads up, Jonas. I *hope* nobody is using those first three 
packages since honestly they're not worth using for any purpose. I had not 
realized / remembered that fakespace and mouse-slider-mode were on Melpa.

I have no interest in maintaining any of these packages, so they probably 
should be removed from Melpa. I'm happy to hand them off to someone else 
to maintain, though I doubt anyone's using them.

**Comment by tarsius** [comment]
Hey! Thanks for the information. I've removed the packages from Melpa.
